In [1]:
input_path  = "/home/jovyan/output/renamed-data/binary/TrainDataUnderSampling.csv"

# Import Package

In [2]:
import time
import pickle
import numpy as np
import pandas as pd

# Read Data

In [3]:
df = pd.read_csv(input_path)
df.head(5)

,Unnamed: 0,flow_id,src_ip,src_port,dst_ip,dst_port,protocol,timestamp,flow_duration,total_fwd_packet,...,fwd_seg_size_min,active_mean,active_std,active_max,active_min,idle_mean,idle_std,idle_max,idle_min,label
0,0,203.73.24.75-192.168.2.109-80-2121-6,203.73.24.75,80,192.168.2.109,2121,6,12/06/2010 09:33:30 PM,824776,5,...,20,0.0,0.0,0.0,0.0,1.276353e+15,0.000000e+00,1.276353e+15,1.276353e+15,0
1,1,192.168.2.111-66.179.20.163-3655-80-6,192.168.2.111,3655,66.179.20.163,80,6,12/06/2010 11:05:38 PM,49287464,3,...,20,0.0,0.0,0.0,0.0,6.381794e+14,9.025219e+14,1.276359e+15,4.928731e+07,0
2,2,203.73.24.75-192.168.2.109-80-3828-6,203.73.24.75,80,192.168.2.109,3828,6,13/06/2010 07:05:34 AM,2922422,42,...,20,0.0,0.0,0.0,0.0,1.276388e+15,0.000000e+00,1.276388e+15,1.276388e+15,0
3,3,192.168.4.121-192.168.5.122-51526-143-6,192.168.4.121,51526,192.168.5.122,143,6,12/06/2010 11:19:52 AM,31006,14,...,20,0.0,0.0,0.0,0.0,1.276316e+15,0.000000e+00,1.276316e+15,1.276316e+15,0
4,4,172.16.2.13-82.255.155.203-2069-6047-6,172.16.2.13,2069,82.255.155.203,6047,6,08/10/2007 09:25:41 PM,44055886,11,...,20,1623322.0,0.0,1623322.0,1623322.0,5.959268e+14,8.427677e+14,1.191854e+15,4.243256e+07,0

In [4]:
df.shape

(218134, 85)

In [5]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 218134 entries, 0 to 218133
Data columns (total 85 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Unnamed: 0                  218134 non-null  int64
 1   flow_id                     218134 non-null  object
 2   src_ip                      218134 non-null  object
 3   src_port                    218134 non-null  int64
 4   dst_ip                      218134 non-null  object
 5   dst_port                    218134 non-null  int64
 6   protocol                    218134 non-null  int64
 7   timestamp                   218134 non-null  object
 8   flow_duration               218134 non-null  int64
 9   total_fwd_packet            218134 non-null  int64
 10  total_bwd_packets           218134 non-null  int64
 11  total_length_of_fwd_packet  218134 non-null  float64
 12  total_length_of_bwd_packet  218134 non-null  float64
 13  fwd_packet_length_max       218134 non-null  float64
 14  fwd_packet_length_min       218134 non-null  float64
 15  fwd_packet_length_mean      218134 non-null  float64
 16  fwd_packet_length_std       218134 non-null  float64
 17  bwd_packet_length_max       218134 non-null  float64
 18  bwd_packet_length_min       218134 non-null  float64
 19  bwd_packet_length_mean      218134 non-null  float64
 20  bwd_packet_length_std       218134 non-null  float64
 21  flow_bytes_per_s            218134 non-null  float64
 22  flow_packets_per_s          218134 non-null  float64
 23  flow_iat_mean               218134 non-null  float64
 24  flow_iat_std                218134 non-null  float64
 25  flow_iat_max                218134 non-null  float64
 26  flow_iat_min                218134 non-null  float64
 27  fwd_iat_total               218134 non-null  float64
 28  fwd_iat_mean                218134 non-null  float64
 29  fwd_iat_std                 218134 non-null  float64
 30  fwd_iat_max                 218134 non-null  float64
 31  fwd_iat_min                 218134 non-null  float64
 32  bwd_iat_total               218134 non-null  float64
 33  bwd_iat_mean                218134 non-null  float64
 34  bwd_iat_std                 218134 non-null  float64
 35  bwd_iat_max                 218134 non-null  float64
 36  bwd_iat_min                 218134 non-null  float64
 37  fwd_psh_flags               218134 non-null  int64
 38  bwd_psh_flags               218134 non-null  int64
 39  fwd_urg_flags               218134 non-null  int64
 40  bwd_urg_flags               218134 non-null  int64
 41  fwd_header_length           218134 non-null  int64
 42  bwd_header_length           218134 non-null  int64
 43  fwd_packets_per_s           218134 non-null  float64
 44  bwd_packets_per_s           218134 non-null  float64
 45  packet_lenght_min           0 non-null       float64
 46  packet_lenght_max           0 non-null       float64
 47  packet_lenght_mean          0 non-null       float64
 48  packet_lenght_std           0 non-null       float64
 49  packet_length_variance      218134 non-null  float64
 50  fin_flag_count              218134 non-null  int64
 51  syn_flag_count              218134 non-null  int64
 52  rst_flag_count              218134 non-null  int64
 53  psh_flag_count              218134 non-null  int64
 54  ack_flag_count              218134 non-null  int64
 55  urg_flag_count              218134 non-null  int64
 56  cwr_flag_count              218134 non-null  int64
 57  ece_flag_count              218134 non-null  int64
 58  down_per_up_ratio           218134 non-null  float64
 59  average_packet_size         218134 non-null  float64
 60  fwd_segment_size_avg        218134 non-null  float64
 61  bwd_segment_size_avg        218134 non-null  float64
 62  fwd_bytes_per_bulk_avg      218134 non-null  int64
 63  fwd_packet_per_bulk_avg     218134 non-null  int64
 64  fwd_bulk_rate_avg           218134 non-null  int64
 65  bwd_bytes_per_bulk_avg      218134 non-null  int64
 66  bwd_packet_per_bulk_avg     218134 non-null  int64
 67  bwd_bulk_rate_avg           218134 non-null  int64
 68  subflow_fwd_packets         218134 non-null  int64
 69  subflow_fwd_bytes           218134 non-null  int64
 70  subflow_bwd_packets         218134 non-null  int64
 71  subflow_bwd_bytes           218134 non-null  int64
 72  fwd_init_win_bytes          218134 non-null  int64
 73  bwd_init_win_bytes          218134 non-null  int64
 74  fwd_act_data_pkts           218134 non-null  int64
 75  fwd_seg_size_min            218134 non-null  int64
 76  active_mean                 218134 non-null  float64
 77  active_std                  218134 non-null  float64
 78  active_max                  218134 non-null  float64
 79  active_min                  218134 non-null  float64
 80  idle_mean                   218134 non-null  float64
 81  idle_std                    218134 non-null  float64
 82  idle_max                    218134 non-null  float64
 83  idle_min                    218134 non-null  float64
 84  label                       218134 non-null  int64
dtypes: float64(45), int64(36), object(4)
memory usage: 141.5+ MB

In [6]:
df.label.value_counts()

0    109067
1    109067
Name: label, dtype: int64